language: java

cache:
  directories:
  - $HOME/.m2

install:
  - ./mvnw install --batch-mode

# Check for errors
script:
  - FLINK_PARCEL/prepare.sh
  - ./mvnw exec:java@validate-parcel --batch-mode
  - ./mvnw exec:java@validate-service --batch-mode
