language: java

cache:
  directories:
  - $HOME/.m2

install:
  - ./mvnw install

# Check for errors
script:
  - FLINK_PARCEL/prepare.sh
  - ./mvnw exec:java@validate-parcel
  - ./mvnw exec:java@validate-service
